# Generated by Django 3.0.8 on 2020-08-29 07:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200710_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mainimage',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
